### PR TITLE
fix/909-invalid-json

### PR DESCRIPTION
**Pull request by lewisdaly**
- Add --silent flag to npm run audit:check to ensure we print valid JSON
- bump package version to 7.2.0

### CODE REVIEW

**Comment by elnyry-sam-k** [comment]
@lewisdaly thanks for this. Can we use to also update the dependencies as per d-bot suggestions (in other PRs).. Also another minor update to the version (7.4.0 now)

**Comment by lewisdaly** [comment]
@elnyry will do. I am however having some trouble with upgrading some packages to use the latest versions of `@mojaloop/central-services-shared` as it looks like a lot of logic around error handling was removed (and I can't seem to find it in `central-services-error-handling`). 

Do you think I should spin that into it's own ticket? Upgrading packages that are currently on `v5.2.X` of `@mojaloop/central-services-shared` looks like it may require some heavy refactoring.

**Comment by lewisdaly** [comment]
Follow up for other dependencies: https://github.com/mojaloop/project/issues/950

**Review by rmothilal — APPROVED** [review]
Happy

**Pull request merged**
